spring:
  application:
    name: document-generation-system

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${PASSWORD:kali}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
